project:
  type: website

website:
  title: "OpenSeat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  echo: true
  eval: true
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



